#theming

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

#customization

title: Matteo Gioia
description: PhD student in Data Science @ Sapienza University of Rome