#theming

remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
- jekyll-include-cache 
- jekyll-remote-theme # add this line to the plugins list if you already have one

#customization

title: Matteo Gioia
description: Here you can find info about me and my latest projects
